version: '3.9'
services:
  postgres:
    image: postgres:15.3-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crew-schedule
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  # pg-admin:
  #   image: dpage/pgadmin4:7.2
  #   container_name: pg-admin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #     PGADMIN_LISTEN_PORT: 5050
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #     PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
  #   ports:
  #     - "5050:5050"
volumes:
  db: ~
